//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoboScanner.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string UILang {
            get {
                return ((string)(this["UILang"]));
            }
            set {
                this["UILang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera1Id {
            get {
                return ((string)(this["Camera1Id"]));
            }
            set {
                this["Camera1Id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Camera2Id {
            get {
                return ((string)(this["Camera2Id"]));
            }
            set {
                this["Camera2Id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double TopDistanceMm {
            get {
                return ((double)(this["TopDistanceMm"]));
            }
            set {
                this["TopDistanceMm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double SideDistanceMm {
            get {
                return ((double)(this["SideDistanceMm"]));
            }
            set {
                this["SideDistanceMm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double RefLengthMm {
            get {
                return ((double)(this["RefLengthMm"]));
            }
            set {
                this["RefLengthMm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double RefWidthMm {
            get {
                return ((double)(this["RefWidthMm"]));
            }
            set {
                this["RefWidthMm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double RefHeightMm {
            get {
                return ((double)(this["RefHeightMm"]));
            }
            set {
                this["RefHeightMm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KTop {
            get {
                return ((double)(this["KTop"]));
            }
            set {
                this["KTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double KSide {
            get {
                return ((double)(this["KSide"]));
            }
            set {
                this["KSide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MmPerPxTop {
            get {
                return ((double)(this["MmPerPxTop"]));
            }
            set {
                this["MmPerPxTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MmPerPxSide {
            get {
                return ((double)(this["MmPerPxSide"]));
            }
            set {
                this["MmPerPxSide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseAdaptive {
            get {
                return ((bool)(this["UseAdaptive"]));
            }
            set {
                this["UseAdaptive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("41")]
        public int AdaptiveBlockSize {
            get {
                return ((int)(this["AdaptiveBlockSize"]));
            }
            set {
                this["AdaptiveBlockSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int AdaptiveC {
            get {
                return ((int)(this["AdaptiveC"]));
            }
            set {
                this["AdaptiveC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseClahe {
            get {
                return ((bool)(this["UseClahe"]));
            }
            set {
                this["UseClahe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.5")]
        public double ClaheClipLimit {
            get {
                return ((double)(this["ClaheClipLimit"]));
            }
            set {
                this["ClaheClipLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int ClaheTileGrid {
            get {
                return ((int)(this["ClaheTileGrid"]));
            }
            set {
                this["ClaheTileGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int BlurKernel {
            get {
                return ((int)(this["BlurKernel"]));
            }
            set {
                this["BlurKernel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Invert {
            get {
                return ((bool)(this["Invert"]));
            }
            set {
                this["Invert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double MinAreaPct {
            get {
                return ((double)(this["MinAreaPct"]));
            }
            set {
                this["MinAreaPct"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MmPerPxTop2 {
            get {
                return ((double)(this["MmPerPxTop2"]));
            }
            set {
                this["MmPerPxTop2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.250")]
        public string LaserHost {
            get {
                return ((string)(this["LaserHost"]));
            }
            set {
                this["LaserHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int LaserPollMs {
            get {
                return ((int)(this["LaserPollMs"]));
            }
            set {
                this["LaserPollMs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int LaserSensor1Inst {
            get {
                return ((int)(this["LaserSensor1Inst"]));
            }
            set {
                this["LaserSensor1Inst"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("101")]
        public int LaserSensor2Inst {
            get {
                return ((int)(this["LaserSensor2Inst"]));
            }
            set {
                this["LaserSensor2Inst"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("102")]
        public int LaserSensor3Inst {
            get {
                return ((int)(this["LaserSensor3Inst"]));
            }
            set {
                this["LaserSensor3Inst"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int LaserAxisXSensor {
            get {
                return ((int)(this["LaserAxisXSensor"]));
            }
            set {
                this["LaserAxisXSensor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int LaserAxisYSensor {
            get {
                return ((int)(this["LaserAxisYSensor"]));
            }
            set {
                this["LaserAxisYSensor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int LaserAxisZSensor {
            get {
                return ((int)(this["LaserAxisZSensor"]));
            }
            set {
                this["LaserAxisZSensor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double LaserAxisXOffsetMm {
            get {
                return ((double)(this["LaserAxisXOffsetMm"]));
            }
            set {
                this["LaserAxisXOffsetMm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double LaserAxisYOffsetMm {
            get {
                return ((double)(this["LaserAxisYOffsetMm"]));
            }
            set {
                this["LaserAxisYOffsetMm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double LaserAxisZOffsetMm {
            get {
                return ((double)(this["LaserAxisZOffsetMm"]));
            }
            set {
                this["LaserAxisZOffsetMm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("118")]
        public int LaserSensor1Offset {
            get {
                return ((int)(this["LaserSensor1Offset"]));
            }
            set {
                this["LaserSensor1Offset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int LaserSensor2Offset {
            get {
                return ((int)(this["LaserSensor2Offset"]));
            }
            set {
                this["LaserSensor2Offset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int LaserSensor3Offset {
            get {
                return ((int)(this["LaserSensor3Offset"]));
            }
            set {
                this["LaserSensor3Offset"] = value;
            }
        }
    }
}
